--local TOCNAME, _ = ...
--local BOM = BuffomatAddon ---@type BuffomatAddon
--
-- ---@class BomBuffModule
--local buffModule = BuffomatModule.DeclareModule("Buff") ---@type BomBuffModule
--
--BOM.Class = BOM.Class or {}
--
-----
----- A class grouping multiple buffs of same type together
-----
-- ---@class BomBuff
-- ---@field title string Name for a class of buffs, to be displayed
-- ---@field spellIds table<number> A list of spellids, indexes in AllSpells
--
-- ---@type BomBuff
--BOM.Class.BuffClass = {}
--BOM.Class.BuffClass.__index = BOM.Class.BuffClass
--
--local CLASS_TAG = "buffclass"
--
-- ---Creates a new BuffClass
-- ---@param title string
-- ---@param spellIds table<number>
-- ---@return BomBuff
--function BOM.Class.BuffClass:new(title, spellIds)
--  local fields = fields or {} ---@type BomBuff
--  setmetatable(fields, BOM.Class.BuffClass)
--
--  fields.t = CLASS_TAG
--  fields.title = title
--  fields.spellIds = spellIds
--
--  return fields
--end
